### ISSUE TITLE
Add XML dump support

### ISSUE THREAD

**Issue by jayvdb** [abuccts/wiktionary-lookup#2]
Small requests using the API page by page is not a problem, if the usage is low.

However for doing large data extraction, using the API is neither acceptable, nor reliable.

See https://www.mediawiki.org/wiki/API:Etiquette and https://meta.wikimedia.org/wiki/Data_dumps

**Comment by abuccts** [comment]
Hi John, I create a new project [enwiktionary2cmudict](https://github.com/abuccts/enwiktionary2cmudict) and pronunciation extraction from XML dump will be implemented there.
